# -*- coding: utf-8 -*-
"""test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yeytRv0wk-MGty7b5zyhLxcDQZgfFOdt
"""

import streamlit as st
import requests
import pandas as pd
import io

st.title('Nintendo And Rockstar Stock Forecast')
stocks = ('NTDOY', 'TTWO')
selected_stock = st.selectbox('Select stock for prediction', stocks)